### PR TITLE
Make CAPSLOCK bindable

### LINKED ISSUE #30: Cannot bind CAPS LOCK
The scenario is that I'm using QuakeSpasm on Linux and have XKBOPTIONS="ctrl:nocaps" with the intention of using CAPS LOCK as CTRL. Most apps see the CAPS LOCK as a CTRL key, but QuakeSpasm does not. Other games have this issue as well -- seeing CAPS LOCK as CAPS LOCK instead of CTRL -- but those games allow binding CAPS LOCK.

Support for binding CAPS LOCK was added to vkQuake.
Please see https://github.com/Novum/vkQuake/commit/8bfb38e34e8890005b83bbb4aa841315fd05bddf

### PR DESCRIPTION
**Pull request by daftmugi**
(Code from vkQuake.)
Fixes #30.

### CODE REVIEW

**Comment by sezero** [comment]
Have you tested both SDL1.2 and SDL2 versions extensively?

**Comment by sezero** [comment]
SDL-1.2 version behaves weird on my linux/x11, that's possibly an SDL issue.
And I don't know what other quirks are there across different platforms, not
only with SDL1.2 but also with SDL2, so I don't like the idea much. Besides,
it changing the keyboard's capslock state is annoying (agree with Axel here)
So, let's not do this, it's not a super important feature.

**Comment by daftmugi** [comment]
Thank you for looking into this!

I have not tested this with SDL1.2, but I have been using SDL2 and it works as expected.

For Quake and all other games, I personally use the CAPSLOCK key to "walk" instead of SHIFT. Quake is the only game I play that does not allow CAPSLOCK to be bound.

About "changing the keyboard's capslock state is annoying," I can understand this. With a default keyboard layout, that would be annoying! I'll try to clarify. The main part here is that the keyboard layout is different. With `XKBOPTIONS="ctrl:nocaps"` set in `/etc/default/keyboard`, the CAPSLOCK key is not acting like CAPSLOCK. In other words, the keyboard is not changing its capslock state (or light). The CAPSLOCK key is changed to the CTRL key at the OS level.

> "In Debian systems the default keyboard layout is described in `/etc/default/keyboard` and it is shared between X and the console."

For example, in GNOME, Firefox, and other desktop apps, the CAPSLOCK key is CTRL. With this setup, copy/paste is not CTRL-c/CTRL-v keys. Instead, copy/paste is CAPSLOCK-c/CAPSLOCK-v keys. The main key pressed is CAPSLOCK, but the main input sent to the app is CTRL.

As another example with this setup, Wine reads CAPSLOCK as CTRL. So, with a game in Wine, I bind CTRL instead of CAPSLOCK, but I'm using the CAPSLOCK key instead of CTRL.

In short, the CAPSLOCK key's input becomes CTRL with that keyboard layout.

It seems that SDL has made a choice to send the raw keyboard input instead.

I can understand that folks who have not changed their keyboard layout at the OS level would find it odd to bind the CAPSLOCK key to something, since it would change the capslock state. I'd imagine they would avoid binding the CAPSLOCK key. But for those who have overridden the CAPSLOCK key at the OS level to be a different key, shouldn't they have a way to bind the CAPSLOCK key in Quake? Could you please reconsider, since this is  important for a setup like mine and possibly others?

I'm grateful that vkQuake has made CAPSLOCK bindable, since it allows me to bind keys in Quake the way that helps me play and enjoy it. I hope QuakeSpasm can do the same.

**Comment by daftmugi** [comment]
@sezero Could you please explain a little more why you rejected this?

If I understand you correctly, you believe that making an additional key bindable in QuakeSpasm will affect its interaction with SDL. How could exposing a key as bindable affect SDL? Since this is no different than making spacebar, ctrl, alt, or any other key bindable, how would a bindable capslock break QuakeSpasm but not break vkQuake?

You have a concern of "changing the keyboard's capslock state." With the keyboard layout I'm using, the capslock key does not change the capslock state.

Could you please reconsider this, since this is important for a setup and keyboard layout like mine?

**Comment by Novum** [comment]
The problem is that you probably like 1 of the 10 people on earth that do this.

**Comment by daftmugi** [comment]
> @Novum: "The problem is that you probably like 1 of the 10 people on earth that do this."

This is the problem? Your comment is condescending. I thought you were a professional and better than that.

**Comment by Novum** [comment]
It is a problem because code that is added is code you have to support and test.

**Comment by sezero** [comment]
OK, locking this ticket now.

@daftmugi: You can always apply the patch yourself before compiling.

**Pull request closed without merging**
