### PR TITLE
Increase Max Skins to 256

### PR DESCRIPTION
**Pull request by JosiahJack**
Increase maximum skins from 32 to 256.

QME seems capable of creating models with more than 256 skins, but starts to have issues much more than that so 256 seems reasonable.  This allows for some very interesting effects coupled with misc_model (and other qc incarnations of such, such as mapobject_custom) and its user settable animation looping and rate.

### CODE REVIEW

**Comment by sezero** [comment]
@ericwa, please review

**Comment by sezero** [comment]
I'm not particularly fond of this one, especially those additional author-credits where unnecessary.

Waiting for a review from @ericwa and/or @andrei-drexler which would be helpful.

**Comment by JosiahJack** [comment]
> I'm not particularly fond of this one, especially those additional author-credits where unnecessary.

Ah, sorry.  I thought I had purged all my attribution comments.

Anyways a little insight to the changes here since this one can seem somewhat arbitrary:
* MAX_SKINS 32 -> 256:  The old tools are capable of producing an .mdl with up to 512 skins.  Given that we only send this as a byte over the network, limit to 256.  This enables some pretty neat effects that might otherwise be restricted to sprites only.  This one is probably the most useful.
* MAX_MODELS 2048 -> 16384:  The 16384 here is definitely arbitrary, but the increase itself is useful as there are some certain extreme-size maps that are in development by my team that I've seen this limit be hit on.  Seriously doubt anyone would get to even 3000, but if we increase it, may was well do a reasonable future-proof amount.
* MAX_SOUNDS 2048 -> 16384: Similar to MAX_MODELS, though this one is me trying to be proactive.  Never seen this one hit but MAX_SFX I have...
* MAX_SFX 1024 -> 16384: Match max sounds and prevent certain large maps with lots of ambients and custom effects from soft-crashing to console.
* MAX_MOD_KNOWN 2048 -> 8192: Can't really match MAX_MODELS as that one includes brush models, but this should at least be a decent ratio of alias vs brush.  I went with half of the MAX_MODELS value.
* The sound console print update to add "not loaded":  This console message always made me wonder what it meant, particularly the stereo one.  I always assumed it just meant the sound might only play as mono.  Now no one has to guess or try to imply its meaning.

**Comment by Shpoike** [comment]
MAX_MODELS is for precaches, being able to precache more models than the engine is able to know about (MAX_MOD_KNOWN) is utterly pointless.
(the mod_known array does not get cleared on map change, allowing it to reuse previous models without having to reload them from disk every single time, cache-willing, and is thus in greater need of a higher limit than the per-map MAX_MODELS is)
Same with the per-map MAX_SOUNDS and persistent MAX_SFX constants.

bumping the MAX_MODELS and MAX_SOUNDS limits can be problematic on account of the svc_serverinfo message containing each and every named file - resulting in ambiguous server crashes (ie: 'overflow without allowoverflow set' type errors), even with a max packet size of 65k.
FTE and QSS both fall back on their late-precaches feature and splurge the ones that wouldn't have fit over time - something that QS clients cannot currently handle. Sometimes you need something more than just a constant/datatype bump.

**Comment by sezero** [comment]
Based on comments by @Shpoike, I think we should drop this. Maybe MAX_SKINS though, if it's really worth it??

**Comment by JosiahJack** [comment]
> Based on comments by @Shpoike, I think we should drop this. Maybe MAX_SKINS though, if it's really worth it??

I was thinking the same for now.  Going to go do my homework on some of these to see which, if any, of these others are able to be improved within the limitations aforementioned.

Reduced this to just affect maximum skins since it can both fit the byte we network it in and is able to be made with even the old tools.

**Comment by sezero** [comment]
@Shpoike (and  @ericwa, @andrei-drexler, @Novum): any objections?

**Comment by Novum** [comment]
Seems okay, memory overhead is 1120 additional pointers (~9KB on 64 bit). I don't see any code that could get broken just by glancing over it.

**Comment by sezero** [comment]
Is it absolutely worth it though...

**Comment by sezero** [comment]
Not applying this for the moment unless we have a very good reason to. No other engine has MAX_SKINS greater than 32, either.

**Pull request closed without merging**
