### PR TITLE
Increase viewangles roll limit to 180

### PR DESCRIPTION
**Pull request by fabiolimamp**
Quake historically puts a limit of 50 degrees for the player's v_angle Z component.

This limit seems arbitrary however, since the Z roll angle "sticks" and must be managed by the mod either way, and nothing breaks with it increased.

### CODE REVIEW

**Comment by sezero** [comment]
@ericwa, @andrei-drexler: comments, objections?

**Comment by andrei-drexler** [comment]
This looks like a sensible change, but maybe it should be controlled by a cvar (`cl_maxroll`, defaulting to `180`)? That would make it consistent with the pitch limits (`cl_minpitch`/`cl_maxpitch`) and it would allow purists to go back to the original behavior by setting it to `50`.

**Comment by fabiolimamp** [comment]
Per @andrei-drexler suggestion, updated the PR with a new `cl_maxroll` cvar defaulted to 180.

**Comment by andrei-drexler** [comment]
@sezero since you're on a roll, maybe merge this one as well? :)

**Comment by sezero** [comment]
> @sezero since you're on a roll,

Am I? :))

> maybe merge this one as well?

You did not do this in ironwail. And I don't like these kinds
of arbitrary stuff very much. How does other engines compare?

**Comment by sezero** [comment]
OK, looked at joequake, it too limits it with +/-50, same as qs and iw.
(Darkplaces does use +/-180 though.)

So, I am not 100% sure that we need this patch.

**Comment by sezero** [comment]
OK, decided not applying this one for now.

**Comment by andrei-drexler** [comment]
Removing the roll limit is likely useful for this kind of trick: https://x.com/fabiolimamp/status/1524507610472398848 (in order to have a smooth transition no matter the initial player angle). I haven't merged it in IW because modders that care about QS support (the vast majority, I think) wouldn't be able to rely on it.

**Pull request closed without merging**
