### PR TITLE
Merge Ironwail's `nomonsters` cvar

### PR DESCRIPTION
**Pull request by Diordany**
Related to #109

### CODE REVIEW

**Comment by Diordany** [comment]
Cherrypicked @andrei-drexler original commit instead.

**Comment by sezero** [comment]
> Cherrypicked @andrei-drexler original commit instead.

OK, but the commit message referencing `#94` becomes wrong in qs: please remove it, if you can.

**Comment by Diordany** [comment]
> OK, but the commit message referencing `#94` becomes wrong in qs: please remove it, if you can.

Done

**Comment by sezero** [comment]
OK, the patch is in. Let's see if it leads to any unlikely issues.

**Pull request merged**
