### PR TITLE
2 new targets within the original xcode project

### PR DESCRIPTION
**Pull request by atsb**
Ok, this should be the final one :)

1. Current project remains, along with the current targets.
2. Two new targets.  SDL2-64 and SDL2-M1, both targeting the correct arch and with separate SDK versions.

Nice and clean.

### CODE REVIEW

**Comment by sezero** [comment]
@ericwa: What do you think? (Note: Original discussion started in #19, continued at #20, then we landed here.)

**Comment by ericwa** [comment]
The 2 files in `xcuserdata` folders shouldn't be committed to source control AFAIK.

If we can get away without the shared `xcsheme`, that would be preferable (just so there's less unnecessary stuff committed, and maybe less to go wrong when we're working with different / old Xcode versions). Unless these shared schemes are doing anything important?

How does this actually work on an M1 given that the `.dylib`'s in our repo are x86_64/x64/ppc only (I think?) - so won't it be attempting to dynamically link to libraries for the wrong architecture?

Otherwise I'm fine with merging this. (I only have a 10.15 x86_64 system).

**Comment by atsb** [comment]
According to lipo, all libraries and the SDL2 Framework have 4 architectures:
```
lipo -info libvorbis.dylib 
Architectures in the fat file: libvorbis.dylib are: ppc i386 x86_64 arm64
```

So linking is fine on my M1 machine.

**Comment by sezero** [comment]
The dylibs are 4-way (ppc, i386, x86_64, aarch64), the SDL2 framework is 3-way (i686, x86_64, aarch64.)

As for the scheme thingies, @atsb should answer for their necessity

**Comment by atsb** [comment]
I would say the schemes should stay, but the below folder can be deleted:
`MacOSX/QuakeSpasm.xcodeproj/xcuserdata/ats.xcuserdatad `

**Comment by sezero** [comment]
OK, this is in, thanks.

I also pushed these follow-up commits:
https://github.com/sezero/quakespasm/commit/40423a1d2c6d961ed61d31d6828c7c7b5a6bdc58
https://github.com/sezero/quakespasm/commit/f53706392e5003aebf944d03ea7b08026fe0cae2
https://github.com/sezero/quakespasm/commit/0974ef402448b5b18389d90e3df4092d60781c93
https://github.com/sezero/quakespasm/commit/23782d657f702bb5689999d39fd2aaaa1282cc3c

**Pull request merged**
