### PR TITLE
Scale fixes

### PR DESCRIPTION
**Pull request by temx**
Per discussions in #32.

### CODE REVIEW

**Comment by sezero** [comment]
@ericwa, @andrei-drexler, @Novum, @mhQuake, @Shpoike: Comments & improvements are welcome.

**Comment by sezero** [comment]
Tested with https://github.com/Novum/vkQuake/files/9245746/scaletest.zip
and also plain id1. One issue found if we can consider that as an issue:
Save the test_scale map in protocol 999 or record it as a demo, then run
qs-0.94.7: loading the save with protocol 999 or trying to playback the
recorded demo results in an illegible server message error. I guess that
it is unavoidable?

**Comment by sezero** [comment]
Apart from the one issue (non-issue?) I noted above, is there anything
left to do with this?

I _am_ willing to apply this patchset and then make a new qs-0.95.0
release.

**Comment by temx** [comment]
Yeah, that's by design. The good news is you need to set protocol 999 **and** load something that uses (not just declares) `scale`, so hopefully it won't cause a lot of pain. The other options are not supporting scale in statics (which reduces its usefulness quite a bit) or encode it differently (which would require changes in the four engines that already support this).

**Comment by sezero** [comment]
OK, I applied the patches now. Thanks to everyone who has contributed!

**Comment by temx** [comment]
BTW that's regarding network/demos - savegames shouldn't be affected. I just tested and I can load one just fine in 0.93.2. It it failing for you?

**Comment by sezero** [comment]
Hmm, I possibly remembered something wrong and mis-reported thing:  Did a save in protocol 999 from test_scale map, I _can_ load it in 0.94.7 -- sorry for that noise.

**Comment by sezero** [comment]
@temx: BTW, I'm giving credit to you as `temx` using your nick. I can use your name properly if you prefer so and provide it to me.

**Pull request closed without merging**
