### PR TITLE
Upgrading and migrating the XCode Project

### PR DESCRIPTION
**Pull request by atsb**
This allows building on modern macOS machines and Apple Silicon machines.  For this change, the old SDL1 target was removed as 32bit targets are no longer possible on any modern macOS system.

The macOS machines capable of compiling and running 32bit apps are so old by now, that supporting them is simply not worth it.

The minimum SDK is now 11.5 due to the requirement of that minimum by the M1 macOS systems.

This has been tested on both my Intel and my M1 mac.  A universal binary is created upon successful compilation.

### CODE REVIEW

**Comment by sezero** [comment]
First of all, thank you for this.

Second, laugh at me if you want but the only Mac I have is a really old
one with 10.6.8 OS with an old Xcode version :)

So, here are some questions:

- Is it a requirement of new Xcode that `English.lproj` to `Base.lproj`
  rename and that `InfoPlist.strings` being moved to new `en.lproj`?
  If not, I'd like to keep the old projects as they are and create o new
  one, e.g. `QuakeSpasm-New.xcodeproj`, and all three projects can share
  those resources.

- Deployment targets can be relaxed a bit, no? E.g. 10.9 (or 10.12) for
  x86_64 and 11.0 for arm64?

- The new project still seems to have some left-over stuff, e.g. flags
  for i386 and ppc builds - not a problem I guess.

**Comment by atsb** [comment]
1. It is not a requirement, but you get some nice 'reminders' about it within XCode about how it is deprecated and migration is 'highly recommended' ;)
2. For x86_64, Even 10.5 would be ok.  It is that M1 requires at least macOS 11.0 and above.  Since in XCode, the new way is basically to build a universal binary, in architectures there is 'standard architectures intel and apple silicon'.  You can build them separately to target different mac versions if you want it is just that you'll need to manually split them and have one target for intel and another target for M1.
3. I double checked before I did a PR.  I'll check again, I thought I purged it all :)

**Comment by sezero** [comment]
> 1. It is not a requirement, but you get some nice 'reminders' about it within XCode about how it is deprecated and migration is 'highly recommended' ;)

We can live with the nags :)  my preference would be keeping all three projects side by side.

>     2. For x86_64, Even 10.5 would be ok.

SDL supports 10.6+ for x64 macs (and we already have a project targeting it that way), we can bump x64 requirement to 10.9 or 10.12

>   It is that M1 requires at least macOS 11.0 and above.

11.0 is OK for M1, of course

>   Since in XCode, the new way is basically to build a universal binary, in architectures there is 'standard architectures intel and apple silicon'.  You can build them separately to target different mac versions if you want it is just that you'll need to manually split them and have one target for intel and another target for M1.

If we bump the SDK requirement to 11.x, we are good with building a universal app, yes?

>     3. I double checked before I did a PR.  I'll check again, I thought I purged it all :)

Thanks!

**Comment by atsb** [comment]
So what I can do then, I will a new project (QuakeSpasmn-SDL2-New) with the following:

1. A single 64bit target in order to compile out of the box without having to scrub the 32bit and ppc architectures (since it won't let you compile without removing those first).  Targeting 10.9.
2. An M1 target, targeting 11.0.

I'll make a new branch for it and do a separate PR, to keep things clean.

**Comment by atsb** [comment]
#20 is created so this one I am closing.

**Pull request closed without merging**
